### ISSUE TITLE
Provide an AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [readium/r2-testapp-js#15]
https://github.com/readium/r2-testapp-js/blob/8f3f6dfe680d37ef8677bd97be7d73feefd2aebd/package.json#L140

Would you be interested in a pull request that would build and upload an [AppImage](https://appimage.org/) for Linux for each build using [Travis CI](http://travis-ci.com/)?

**Comment by danielweck** [comment]
I imagine your are referring to
https://github.com/probonopd/uploadtool/blob/master/upload.sh
?

**Comment by probonopd** [comment]
Hi @danielweck great to see you have added a `.travis.yml` file. Very useful, thank you. Yes, the uploadtool can be used to upload continuous builds to GitHub Releases. But first they need to be built "green" ;-)

**Comment by danielweck** [comment]
I'm trying the Docker image provided by `electron-builder`, to build for Linux and Windows (via Wine).
The second build target in the TravisCI matrix is MacOS, which seems to work fine so far. I am tweaking the script to upload GitHub draft releases from the develop branch. I might need to throttle that down, maybe using a separate branch dedicated to building test releases.

**Comment by probonopd** [comment]
Yes, many projects build on Travis CI using `electron-builder`. Not sure whether you need Docker.

https://github.com/probonopd/uploadtool/blob/master/upload.sh can upload every build to a release called "continuous", it will replace the pre-existing binaries with the latest one. So there is always exactly one contunous build available for download.

**Comment by danielweck** [comment]
Thank you for suggesting your script!
Maybe we will use it.

Right now, we have a working setup it seems (just needs to be refined):

https://travis-ci.org/readium/r2-testapp-js/builds/479521643

https://github.com/readium/r2-testapp-js/releases/tag/untagged-924aaf86662e64fb45fd
